In [1]:
import numpy
import numpy as np
numpy.__version__

'1.16.5'

In [20]:
#np的slice是參考，跟python原本list的slice是複製不一樣
#np slice出來得參考會影響到原本的np array
#要建立np array的複本要用 .copy()

In [3]:
x = np.array([(12, 5, 2, 4), (7, 6, 8, 8), (1, 6, 7, 7)])
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [7]:
#slice, row col 
#一般的 [[list]],[list]]無法這樣slice 
x[1:,1:] ,x[1:,2]

(array([[6, 8, 8],
        [6, 7, 7]]), array([8, 7]))

In [9]:
x[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [12]:
#單取col成array
x[:,1] 

array([5, 6, 6])

In [14]:
#單取row成array
x[2,:] 

array([1, 6, 7, 7])

In [16]:
#fancy_index
y = np.random.randint(100,size=10)
fancy_index = [3,6,9]
y, y[fancy_index]

(array([70, 48, 20, 38, 75, 51, 93, 68, 90, 43]), array([38, 93, 43]))

In [19]:
x = np.arange(10)
fancy_index = np.array([2,5,7])
x[fancy_index]=100
x

array([  0,   1, 100,   3,   4, 100,   6, 100,   8,   9])