In [8]:
a, b = 9, 10
print(a & b)#line 1 #bit為單位
print(a and b)#line 2 #整體為單位
print(b and a)

8
10
9


In [1]:
#In line 1, a = 1001, b = 1010, Performing & on a and b, gives us 1000 which is the binary value of decimal value 8.
#In line 2, the expression ‘a and b’ first evaluates a; if a is False (or Zero), its value is returned immediately because of “lazy evaluation” explained above, else, b is evaluated. If b is also non-zero then the resulting value is returned.

In [3]:
import numpy as np 
A = np.array([1,0,1,1,0])
B = np.array([0,0,1,0,1])
A & B

array([0, 0, 1, 0, 0], dtype=int32)

In [6]:
#A and B #fail

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[ ( x < 2 ) | ( x > 7 ) ] 

array([0, 1, 8, 9])