In [8]:
a, b = 9, 10
#9  -> 1001
#10 -> 1010

#bit為單位
print(a & b)

#整體為單位，判断变量是否为0，是0则为False，非0判断为True，
#and中含0，返回0； 均为非0时，返回后一个值，
print(1 and 3)
print(0 and 3)
print(3 and 0)

# or中，至少有一个非0时，返回第一个非0
print(0 or 0)
print(1 or 3)

8
3
0
0
0
1


In [1]:
#In line 1, a = 1001, b = 1010, Performing & on a and b, gives us 1000 which is the binary value of decimal value 8.
#In line 2, the expression ‘a and b’ first evaluates a; if a is False (or Zero), its value is returned immediately because of “lazy evaluation” explained above, else, b is evaluated. If b is also non-zero then the resulting value is returned.

In [3]:
import numpy as np 
A = np.array([1,0,1,1,0])
B = np.array([0,0,1,0,1])
A & B

array([0, 0, 1, 0, 0], dtype=int32)

In [6]:
#A and B #fail

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[ ( x < 2 ) | ( x > 7 ) ] 

array([0, 1, 8, 9])