In [2]:
import numpy
import numpy as np
numpy.__version__

'1.16.5'

In [37]:
np.array([1, 5, 3])

array([1, 5, 3])

In [38]:
#自動轉成同型態
np.array([3.24, 3, 5])

array([3.24, 3.  , 5.  ])

In [39]:
#自動轉成同型態
np.array(['cat',3])

array(['cat', '3'], dtype='<U3')

In [40]:
np.array([3, 5],dtype=str)

array(['3', '5'], dtype='<U1')

In [3]:
#多維
np.array([(3, 2),(3, 5),(7, 6)])

array([[3, 2],
       [3, 5],
       [7, 6]])

In [4]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [44]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full((2, 5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [46]:
np.full((2,5,3),3.2)

array([[[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]],

       [[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]]])

In [47]:
np.linspace(0, 20, 4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [48]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [49]:
#random uniform
np.random.random((2, 5)) 

array([[0.19287392, 0.65604331, 0.26114307, 0.4883973 , 0.13421826],
       [0.99070191, 0.07332831, 0.97141642, 0.93487135, 0.21246816]])

In [50]:
#random normal 
#distribution mean 0 std 1  
np.random.normal(0,1,(2,5)) 

array([[-0.12132021, -1.86282655,  1.97145212,  1.33237387,  0.14609348],
       [-0.47837954, -0.45443326, -0.5409726 ,  0.38115128,  0.13522958]])

In [51]:
#random integer
np.random.randint(0,100,(2,5))

array([[51,  5, 88, 59, 94],
       [64, 87, 35, 66, 89]])

In [52]:
#單位矩陣
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.eye(3)*4 

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [54]:
a = np.random.randint(10,size=(2,5,4))
a

array([[[2, 0, 3, 2],
        [6, 9, 8, 7],
        [3, 7, 8, 9],
        [8, 2, 0, 0],
        [7, 0, 6, 4]],

       [[3, 0, 0, 2],
        [9, 7, 1, 8],
        [4, 1, 2, 3],
        [5, 3, 1, 7],
        [4, 8, 8, 6]]])

In [55]:
a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes
# ndim means dimensions of array
# itemsize(byte), nbytes(byte)
# in general, itemsize * size = nbytes

(3, (2, 5, 4), 40, dtype('int32'), 4, 160)