In [1]:
import numpy
import numpy as np
numpy.__version__

'1.16.5'

In [2]:
#np的這種量化化計算稱作ufunction (universal function)
#np的向量化計算 比python自己的迭代快很多
#盡量用numpy的fn 因為效能考量

np.random.seed(0)

#計算倒數
def reciprocals( vals ):
    result = np.empty(len(vals))
    for i in range(len(vals)):
        result[i] = 1/vals[i]
    return result

In [4]:
#slow
%timeit reciprocals(np.random.randint(1,100,size=1000000)) 

213 ms ± 62.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
#fast
%timeit (1/np.random.randint(1,10,size=1000000)) 

13.5 ms ± 23.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
a = np.arange(9).reshape(3,3)
b = a * 2
c = 2 ** a
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [9]:
c

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [11]:
a = np.arange(5)
a + 5 , a **2 , 1 / a , -a

ipykernel_launcher:2: RuntimeWarning: divide by zero encountered in true_divide


(array([5, 6, 7, 8, 9]),
 array([ 0,  1,  4,  9, 16], dtype=int32),
 array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ]),
 array([ 0, -1, -2, -3, -4]))

In [12]:
x = np.arange(10)
x < 4, np.count_nonzero( x < 4 ), np.sum( x < 4 )

(array([ True,  True,  True,  True, False, False, False, False, False,
        False]), 4, 4)

In [14]:
np.all( x < 4 ), np.any( x < 4 )

(False, True)

In [15]:
x[ x < 4 ]

array([0, 1, 2, 3])

In [16]:
#三角函數
theta = np.linspace(0, np.pi*2 , 5)
theta

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [17]:
np.sin(theta)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [19]:
import math
math.sin(math.pi), np.allclose(math.sin(math.pi),0)

(1.2246467991473532e-16, True)

In [20]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [21]:
np.exp([1,2,3]), np.power(3,[1,2,3])

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([ 3,  9, 27], dtype=int32))

In [22]:
np.log([1,2,4,10]), np.log10([1,2,4,10])

(array([0.        , 0.69314718, 1.38629436, 2.30258509]),
 array([0.        , 0.30103   , 0.60205999, 1.        ]))