In [1]:
import numpy
import numpy as np
numpy.__version__

'1.19.2'

In [2]:
# ndarray是numpy的物件，代表n-dimension array
# 下面介紹將ndarray實例化的各種方法

In [3]:
np.array([1, 5, 3])

array([1, 5, 3])

In [4]:
# numpy.ndarray
type(np.array([1, 5, 3]))

numpy.ndarray

In [5]:
#自動轉成同型態 ndarray必為同形態
np.array([3.24, 3, 5])

array([3.24, 3.  , 5.  ])

In [7]:
#自動轉成同型態
np.array(['cat',3])

array(['cat', '3'], dtype='<U3')

In [8]:
np.array([3, 5],dtype=str)

array(['3', '5'], dtype='<U1')

In [9]:
#多維
np.array([(3, 2),(3, 5),(7, 6)])

array([[3, 2],
       [3, 5],
       [7, 6]])

In [10]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [13]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((2, 5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [16]:
np.full((2,5,3),3.2)

array([[[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]],

       [[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]]])

In [18]:
np.linspace(0, 20, 4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [19]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [20]:
#random uniform
np.random.random((2, 5)) 

array([[0.47258575, 0.48166026, 0.3368357 , 0.83898275, 0.73496384],
       [0.88155234, 0.02420365, 0.61570132, 0.04116852, 0.94531213]])

In [23]:
#random normal 
#distribution mean 0 std 1 （standard normal) 
np.random.normal(0,1,(2,5)) 

array([[-1.27778471, -2.29552062, -0.20633781,  0.36564118,  0.85624014],
       [-0.69999431, -0.21250634, -0.32363986, -0.16766927,  0.31201694]])

In [24]:
#random integer
np.random.randint(0,100,(2,5))

array([[54, 72, 46, 50, 58],
       [77,  3, 39, 47,  9]])

In [25]:
#單位矩陣
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3)*4 

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [27]:
a = np.random.randint(10,size=(2,5,4))
a

array([[[8, 5, 1, 3],
        [4, 5, 7, 8],
        [4, 7, 2, 3],
        [0, 9, 0, 2],
        [5, 7, 6, 7]],

       [[8, 7, 9, 3],
        [0, 8, 9, 8],
        [3, 5, 5, 8],
        [7, 0, 8, 5],
        [5, 6, 7, 4]]])

In [28]:
a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes
# ndim means dimensions of array
# itemsize(byte), nbytes(byte)
# in general, itemsize * size = nbytes

(3, (2, 5, 4), 40, dtype('int64'), 8, 320)