In [2]:
import numpy as np
import math
import random
np.__version__

'1.16.5'

In [ ]:
#對於小規模操作，Python有可能較快，而對於大規模（向量）操作，numpy的速度要快得多
# ms 毫秒 Millisecond 1 毫秒=10-3秒
# μs 微秒 Microsecond 1 微秒=10-6秒
# ns 奈秒 Nanosecond  1 奈秒=10-9秒

In [6]:
#小規模
%timeit math.log(10)
%timeit np.log(10)

88 ns ± 0.176 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
618 ns ± 0.719 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
#小規模
%timeit math.exp(3)
%timeit np.exp(3)

102 ns ± 0.305 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
619 ns ± 1.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
#大規模
ndArr = np.arange(10000)
%timeit random.choices(ndArr, k=1000)
%timeit np.random.choice(ndArr, size=1000)

207 µs ± 2.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
20.7 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
#倒數
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [21]:
#大規模
ndArr1 = np.arange(1,100000)

%timeit compute_reciprocals(ndArr1)
%timeit 1/ndArr1

134 ms ± 183 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
89.4 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#memory layout
#col base or row base

In [4]:
x = np.random.standard_normal((1000000, 5))  
x

array([[ 0.93790931,  0.21015479,  0.76634021, -0.11887548,  0.70471803],
       [ 1.51363038, -0.7214616 ,  0.87545863, -1.47554463,  0.75732038],
       [-0.25870138,  1.21145058, -0.88658604,  1.39496184, -0.05357512],
       ...,
       [ 1.12929347,  0.46455709,  1.10791216, -1.27231747,  0.79592319],
       [ 0.19637552, -1.15006139,  1.36197123,  0.46406391,  0.95218531],
       [-1.03175106,  1.23203783,  0.81261087,  0.21256863,  0.41029248]])

In [5]:
y = 2 * x + 3
y  

array([[4.87581862, 3.42030958, 4.53268042, 2.76224904, 4.40943606],
       [6.02726077, 1.55707679, 4.75091725, 0.04891074, 4.51464076],
       [2.48259724, 5.42290116, 1.22682793, 5.78992369, 2.89284977],
       ...,
       [5.25858694, 3.92911419, 5.21582433, 0.45536505, 4.59184637],
       [3.39275104, 0.69987721, 5.72394246, 3.92812782, 4.90437061],
       [0.93649788, 5.46407566, 4.62522174, 3.42513726, 3.82058496]])

In [7]:
C = np.array((x, y), order='C')  
F = np.array((x, y), order='F') 

In [9]:
%timeit C.sum()  
%timeit F.sum()  

10.3 ms ± 65 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
10.3 ms ± 89.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%timeit C.sum(axis=0)  
%timeit F.sum(axis=0)  

16.2 ms ± 384 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
51.3 ms ± 675 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%timeit C.sum(axis=1) 
%timeit F.sum(axis=1)  

22.8 ms ± 120 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
46.5 ms ± 611 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
