In [2]:
import numpy
import numpy as np
numpy.__version__

'1.16.5'

In [3]:
import numpy as np

In [4]:
np.array([1, 5, 3])

array([1, 5, 3])

In [5]:
np.array([3.24, 3, 5])#自動轉成同型態

array([3.24, 3.  , 5.  ])

In [6]:
np.array(['cat',3])

array(['cat', '3'], dtype='<U3')

In [7]:
np.array([3, 5],dtype=str)

array(['3', '5'], dtype='<U1')

In [8]:
np.array([(3, 2),(3, 5),(7, 6)])#多維

array([[3, 2],
       [3, 5],
       [7, 6]])

In [9]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [11]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((2, 5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [13]:
np.full((2,5,3),3.2)

array([[[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]],

       [[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]]])

In [14]:
np.linspace(0, 20, 4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [15]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [16]:
np.random.random((2, 5)) #uniform

array([[0.737768  , 0.34615891, 0.38770005, 0.7340625 , 0.74350514],
       [0.38242206, 0.01755106, 0.93810902, 0.71705072, 0.61462592]])

In [17]:
np.random.normal(0,1,(2,5)) #normal distribution mean 0 std 1  

array([[ 0.91481707,  1.52975264,  1.95541881, -0.26644038,  0.18206027],
       [ 2.35282049,  1.53613638, -1.2444504 ,  0.64424342,  0.26460946]])

In [18]:
np.random.randint(0,100,(2,5))

array([[ 2, 88, 57, 71, 35],
       [88, 73, 53,  8, 78]])

In [19]:
np.eye(3)*4 #單位矩陣

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [20]:
a = np.random.randint(10,size=(2,5,3))
a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes
#itemsize(byte), nbytes(byte)
# in general, itemsize * size = nbytes

(3, (2, 5, 3), 30, dtype('int32'), 4, 120)

In [21]:
#slice
x = np.array([(12, 5, 2, 4), (7, 6, 8, 8), (1, 6, 7, 7)])
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
x[1:,1:] #slice, row col u [[list]],[list]]無法這樣slice 

array([[6, 8, 8],
       [6, 7, 7]])

In [23]:
x[1:,2]

array([8, 7])

In [24]:
x[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [25]:
x[:,1] #單取col成array

array([5, 6, 6])

In [26]:
x[2,:] #單取row成array

array([1, 6, 7, 7])

In [27]:
#np的slice是參考，跟python原本list的slice是複製不一樣
#np slice出來得參考會影響到原本的np array
#要建立np array的複本要用 .copy()

In [28]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
#相同維度的串接
x1 = np.array([1, 2, 3])
y1 = np.array([4, 5, 6])

In [30]:
np.concatenate([x1,y1])

array([1, 2, 3, 4, 5, 6])

In [31]:
#不同維度的串接
x2 = np.array([(3, 2),(3, 5),(7, 6)])
y2 = np.array([(5, 0)])
z2 = np.array([[1], [3], [6]])

In [32]:
x2

array([[3, 2],
       [3, 5],
       [7, 6]])

In [33]:
y2

array([[5, 0]])

In [34]:
z2

array([[1],
       [3],
       [6]])

In [35]:
np.vstack( [x2, y2] )

array([[3, 2],
       [3, 5],
       [7, 6],
       [5, 0]])

In [36]:
np.hstack( [x2, z2] )

array([[3, 2, 1],
       [3, 5, 3],
       [7, 6, 6]])

In [37]:
a, b, c = np.split(np.array((2,5,6,7,3,6,3,6)), [2,5]  )
a, b, c

(array([2, 5]), array([6, 7, 3]), array([6, 3, 6]))

In [38]:
a, b = np.vsplit( np.arange(16).reshape([4,4]), [2] )
a, b

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [39]:
c, d = np.hsplit( np.arange(16).reshape([4,4]), [2] )
c, d

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [40]:
#np的這種量化化計算稱作ufunction (universal function)
#np的向量化計算 比python自己的迭代快很多

np.random.seed(0)

def reciprocals( vals ):
    result = np.empty(len(vals))
    for i in range(len(vals)):
        result[i] = 1/vals[i]
    return result

In [41]:
%timeit reciprocals(np.random.randint(1,100,size=1000000)) #slow

206 ms ± 476 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [42]:
%timeit (1/np.random.randint(1,10,size=1000000)) #fast

13.9 ms ± 87.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
a = np.arange(9).reshape(3,3)
b = a * 2
c = 2 ** a
a

In [45]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [46]:
c

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [57]:
a = np.arange(5)
print( a + 5 , a **2 , 1 / a , -a)

[5 6 7 8 9] [ 0  1  4  9 16] [       inf 1.         0.5        0.33333333 0.25      ] [ 0 -1 -2 -3 -4]


In [61]:
x = np.arange(10)
x < 4, np.count_nonzero( x < 4 ), np.sum( x < 4 )

(array([ True,  True,  True,  True, False, False, False, False, False,
        False]), 4, 4)

In [64]:
np.all( x < 4 ), np.any( x < 4 )

(False, True)

In [65]:
x[ x < 4 ]

array([0, 1, 2, 3])

In [48]:
#三角函數
theta = np.linspace(0, np.pi*2 , 5)
theta

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [49]:
np.sin(theta)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [50]:
import math
math.sin(math.pi), np.allclose(math.sin(math.pi),0)

(1.2246467991473532e-16, True)

In [53]:
np.exp([1,2,3]), np.power(3,[1,2,3])

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([ 3,  9, 27], dtype=int32))

In [57]:
np.log([1,2,4,10]), np.log10([1,2,4,10])

(array([0.        , 0.69314718, 1.38629436, 2.30258509]),
 array([0.        , 0.30103   , 0.60205999, 1.        ]))

In [65]:
#預先決定輸出的記憶體
x = np.arange(5)
y = np.empty(5)
np.multiply(x,12,out=y)

array([ 0., 12., 24., 36., 48.])

In [69]:
a = np.arange(5)
b = np.zeros(10)
np.power(2,x,out=b[::2])
b

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [76]:
x = np.arange(1,6)
np.add.reduce(x), np.multiply.reduce(x), np.add.accumulate(x), np.multiply.accumulate(x)

(15,
 120,
 array([ 1,  3,  6, 10, 15], dtype=int32),
 array([  1,   2,   6,  24, 120], dtype=int32))

In [6]:
#外積
x = np.arange(1,5)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [24]:
#summerise
x = np.random.random(1000000)
%timeit np.sum(x) #快多了
%timeit sum(x)

2.15 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
348 ms ± 33.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
np.sum(x), sum(x)

(499535.6727532691, 499535.6727532379)

In [39]:
#as same as
np.max(x), np.min(x), x.max(), x.min()

(0.9999995418471068,
 2.7761634412426517e-06,
 0.9999995418471068,
 2.7761634412426517e-06)

In [41]:
x.mean(), x.std()

(0.4995356727532691, 0.28856295353496436)

In [31]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
y.sum(axis=0), y.sum(axis=1)

(array([ 5,  7,  9, 11, 13]), array([10, 35]))

In [45]:
a = np.random.random((10,3))
a

array([[0.48727154, 0.43625844, 0.07732428],
       [0.0066486 , 0.94809088, 0.3500396 ],
       [0.08313254, 0.99011697, 0.7406364 ],
       [0.33438228, 0.72278816, 0.78728927],
       [0.22370647, 0.54920565, 0.74854962],
       [0.91984855, 0.10386761, 0.05336203],
       [0.15514543, 0.0359925 , 0.21817016],
       [0.50676474, 0.32588892, 0.55714611],
       [0.45791868, 0.05286798, 0.307839  ],
       [0.57987449, 0.85603002, 0.07136737]])

In [49]:
a.mean(axis=0)

array([0.37546933, 0.50211072, 0.39117238])

In [54]:
#broadcasting，可去查詢broadcasting詳細規則
#全部的數減去平均值
b = a - a.mean(axis=0)
b

array([[ 0.11180221, -0.06585227, -0.3138481 ],
       [-0.36882073,  0.44598017, -0.04113278],
       [-0.2923368 ,  0.48800626,  0.34946402],
       [-0.04108705,  0.22067744,  0.39611688],
       [-0.15176287,  0.04709494,  0.35737724],
       [ 0.54437922, -0.3982431 , -0.33781035],
       [-0.2203239 , -0.46611821, -0.17300223],
       [ 0.13129541, -0.17622179,  0.16597372],
       [ 0.08244935, -0.44924274, -0.08333338],
       [ 0.20440515,  0.35391931, -0.31980501]])

In [56]:
#驗算，都接近0
b.mean(axis=0)

array([ 0.00000000e+00, -3.33066907e-17,  3.33066907e-17])