In [13]:
import numpy
import numpy as np
numpy.__version__

'1.16.5'

In [14]:
#相同維度的串接
x1 = np.array([1, 2, 3])
y1 = np.array([4, 5, 6])

In [15]:
np.concatenate([x1,y1])

array([1, 2, 3, 4, 5, 6])

In [16]:
#不同維度的串接
x2 = np.array([(3, 2),(3, 5),(7, 6)])
y2 = np.array([(5, 0)])
z2 = np.array([[1], [3], [6]])

In [17]:
x2

array([[3, 2],
       [3, 5],
       [7, 6]])

In [18]:
y2

array([[5, 0]])

In [19]:
z2

array([[1],
       [3],
       [6]])

In [20]:
np.vstack( [x2, y2] )

array([[3, 2],
       [3, 5],
       [7, 6],
       [5, 0]])

In [21]:
np.hstack( [x2, z2] )

array([[3, 2, 1],
       [3, 5, 3],
       [7, 6, 6]])

In [22]:
a, b, c = np.split(np.array((2,5,6,7,3,6,3,6)), [2,5]  )
a, b, c

(array([2, 5]), array([6, 7, 3]), array([6, 3, 6]))

In [23]:
a, b = np.vsplit( np.arange(16).reshape([4,4]), [2] )
a, b

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [24]:
c, d = np.hsplit( np.arange(16).reshape([4,4]), [2] )
c, d

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [25]:
#預先決定輸出的記憶體
x = np.arange(5)
y = np.empty(5)
np.multiply(x,12,out=y)

array([ 0., 12., 24., 36., 48.])

In [26]:
a = np.arange(5)
b = np.zeros(10)
np.power(2,x,out=b[::2])
b

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [27]:
x = np.arange(1,6)
np.add.reduce(x), np.multiply.reduce(x), np.add.accumulate(x), np.multiply.accumulate(x)

(15,
 120,
 array([ 1,  3,  6, 10, 15], dtype=int32),
 array([  1,   2,   6,  24, 120], dtype=int32))

In [28]:
#外積
x = np.arange(1,5)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [29]:
#summerise
x = np.random.random(1000000)
%timeit np.sum(x) #快多了
%timeit sum(x)

1.78 ms ± 364 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
93.3 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
np.sum(x), sum(x)

(499759.57566147397, 499759.5756614582)

In [31]:
#as same as
np.max(x), np.min(x), x.max(), x.min()

(0.9999986629403189,
 6.440207899194306e-07,
 0.9999986629403189,
 6.440207899194306e-07)

In [32]:
x.mean(), x.std()

(0.49975957566147394, 0.2887715911644051)

In [33]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
y.sum(axis=0), y.sum(axis=1)

(array([ 5,  7,  9, 11, 13]), array([10, 35]))

In [35]:
a = np.random.random((10,3))
a

array([[0.40307107, 0.35039816, 0.1011153 ],
       [0.39788394, 0.2034482 , 0.29594177],
       [0.58992049, 0.33016915, 0.77702013],
       [0.94340564, 0.06017329, 0.57132594],
       [0.32189097, 0.67478118, 0.06384082],
       [0.26779096, 0.48911728, 0.46486055],
       [0.96823996, 0.48016475, 0.69199479],
       [0.13230255, 0.46658056, 0.11318993],
       [0.0192116 , 0.36199732, 0.75677021],
       [0.02430642, 0.64210842, 0.25569125]])

In [36]:
a.mean(axis=0)

array([0.40680236, 0.40589383, 0.40917507])

In [37]:
#broadcasting，可去查詢broadcasting詳細規則
#全部的數減去平均值
b = a - a.mean(axis=0)
b

array([[-0.00373129, -0.05549567, -0.30805977],
       [-0.00891842, -0.20244563, -0.1132333 ],
       [ 0.18311813, -0.07572468,  0.36784506],
       [ 0.53660328, -0.34572054,  0.16215087],
       [-0.08491139,  0.26888734, -0.34533425],
       [-0.1390114 ,  0.08322345,  0.05568548],
       [ 0.5614376 ,  0.07427092,  0.28281972],
       [-0.27449981,  0.06068673, -0.29598514],
       [-0.38759076, -0.04389651,  0.34759514],
       [-0.38249594,  0.23621459, -0.15348382]])

In [38]:
#驗算，都接近0
b.mean(axis=0)

array([ 4.44089210e-17,  2.22044605e-17, -2.22044605e-17])

In [39]:
#sort
x = np.random.randint(1,100,size=10)
np.sort(x)

array([11, 14, 15, 21, 59, 65, 79, 83, 85, 92])

In [40]:
x = np.random.randint(1,100,[4,4])
np.sort(x, axis =0)

array([[36, 12, 27,  7],
       [56, 13, 45,  9],
       [74, 21, 78, 55],
       [89, 47, 97, 63]])

In [41]:
np.sort(x, axis=1)

array([[21, 45, 63, 74],
       [ 7, 47, 89, 97],
       [12, 36, 55, 78],
       [ 9, 13, 27, 56]])

In [42]:
#partition
x = np.random.randint(1,100,size=10)
#最小個值放左側，順序隨意
np.partition(x,3)

array([ 4, 13, 16, 22, 25, 39, 46, 52, 57, 60])

In [43]:
x = np.random.randint(1,100,size=20)
x = x.reshape(4,5)
np.partition(x,2,axis=1)

array([[ 9, 22, 42, 98, 93],
       [36, 52, 57, 58, 95],
       [34, 40, 70, 98, 71],
       [ 1,  7, 42, 55, 48]])