In [4]:
import numpy
numpy.__version__

'1.16.5'

In [2]:
import numpy as np

In [9]:
np.array([1, 5, 3])

array([1, 5, 3])

In [11]:
np.array([3.24, 3, 5])#自動轉成同型態

array([3.24, 3.  , 5.  ])

In [13]:
np.array(['cat',3])

array(['cat', '3'], dtype='<U3')

In [19]:
np.array([3,5],dtype=str)

array(['3', '5'], dtype='<U1')

In [43]:
np.array([(3,2),(3,5),(7,6)])#多維

array([[3, 2],
       [3, 5],
       [7, 6]])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [28]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full((2,5),3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [46]:
np.full((2,5,3),3.2)

array([[[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]],

       [[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]]])

In [32]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [34]:
np.random.random((2,5)) #uniform

array([[0.5765114 , 0.12809911, 0.15957936, 0.387803  , 0.95227374],
       [0.61668601, 0.21039998, 0.13317614, 0.28143099, 0.10474003]])

In [37]:
np.random.normal(0,1,(2,5)) #normal distribution mean 0 std 1  

array([[ 0.8817991 , -1.17031428, -0.8700155 , -0.50188433, -1.08836966],
       [ 0.1058192 , -1.0172433 , -0.7922935 , -1.00369606,  0.01819413]])

In [39]:
np.random.randint(0,100,(2,5))

array([[78, 33,  8, 66, 37],
       [54, 27, 46, 46, 11]])

In [42]:
np.eye(3) #單位矩陣

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
a = np.random.randint(10,size=(2,5,3))
a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes
#itemsize(byte), nbytes(byte)
# in general, itemsize * size = nbytes

(3, (2, 5, 3), 30, dtype('int32'), 4, 120)

In [13]:
#slice
x = np.array([(12, 5, 2, 4), (7, 6, 8, 8), (1, 6, 7, 7)])
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
x[1:,1:] #row col

array([[6, 8, 8],
       [6, 7, 7]])

In [18]:
x[1:,2]

array([8, 7])

In [20]:
x[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [22]:
x[:,1] #單取col成array

array([5, 6, 6])

In [24]:
x[2,:] #單取row成array

array([1, 6, 7, 7])

In [25]:
#np的slice是參考，跟python原本list的slice是複製不一樣
#np slice出來得參考會影響到原本的np array
#要建立np array的複本要用 .copy()

In [4]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
#np的向量化計算 比python自己的迭代快很多
np.random.seed(0)

def reciprocals( vals ):
    result = np.empty(len(vals))
    for i in range(len(vals)):
        result[i] = 1/vals[i]
    return result

In [16]:
%timeit reciprocals(np.random.randint(1,100,size=1000000)) #slow

206 ms ± 803 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%timeit (1/np.random.randint(1,10,size=1000000)) #fast

13.7 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
