In [4]:
import numpy
numpy.__version__

'1.16.5'

In [5]:
import numpy as np

In [9]:
np.array([1, 5, 3])

array([1, 5, 3])

In [11]:
np.array([3.24, 3, 5])#自動轉成同型態

array([3.24, 3.  , 5.  ])

In [13]:
np.array(['cat',3])

array(['cat', '3'], dtype='<U3')

In [19]:
np.array([3,5],dtype=str)

array(['3', '5'], dtype='<U1')

In [43]:
np.array([(3,2),(3,5),(7,6)])#多維

array([[3, 2],
       [3, 5],
       [7, 6]])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [28]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full((2,5),3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [46]:
np.full((2,5,3),3.2)

array([[[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]],

       [[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]]])

In [32]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [34]:
np.random.random((2,5)) #uniform

array([[0.5765114 , 0.12809911, 0.15957936, 0.387803  , 0.95227374],
       [0.61668601, 0.21039998, 0.13317614, 0.28143099, 0.10474003]])

In [37]:
np.random.normal(0,1,(2,5)) #normal distribution mean 0 std 1  

array([[ 0.8817991 , -1.17031428, -0.8700155 , -0.50188433, -1.08836966],
       [ 0.1058192 , -1.0172433 , -0.7922935 , -1.00369606,  0.01819413]])

In [39]:
np.random.randint(0,100,(2,5))

array([[78, 33,  8, 66, 37],
       [54, 27, 46, 46, 11]])

In [42]:
np.eye(3) #單位矩陣

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
a = np.random.randint(10,size=(2,5,3))
a.ndim, a.shape, a.size, a.dtype

(3, (2, 5, 3), 30, dtype('int32'))