In [4]:
import numpy
import numpy as np
numpy.__version__

'1.16.5'

In [29]:
#相同維度的串接
x1 = np.array([1, 2, 3])
y1 = np.array([4, 5, 6])

In [30]:
np.concatenate([x1,y1])

array([1, 2, 3, 4, 5, 6])

In [31]:
#不同維度的串接
x2 = np.array([(3, 2),(3, 5),(7, 6)])
y2 = np.array([(5, 0)])
z2 = np.array([[1], [3], [6]])

In [32]:
x2

array([[3, 2],
       [3, 5],
       [7, 6]])

In [33]:
y2

array([[5, 0]])

In [34]:
z2

array([[1],
       [3],
       [6]])

In [35]:
np.vstack( [x2, y2] )

array([[3, 2],
       [3, 5],
       [7, 6],
       [5, 0]])

In [36]:
np.hstack( [x2, z2] )

array([[3, 2, 1],
       [3, 5, 3],
       [7, 6, 6]])

In [37]:
a, b, c = np.split(np.array((2,5,6,7,3,6,3,6)), [2,5]  )
a, b, c

(array([2, 5]), array([6, 7, 3]), array([6, 3, 6]))

In [38]:
a, b = np.vsplit( np.arange(16).reshape([4,4]), [2] )
a, b

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [39]:
c, d = np.hsplit( np.arange(16).reshape([4,4]), [2] )
c, d

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [55]:
#預先決定輸出的記憶體
x = np.arange(5)
y = np.empty(5)
np.multiply(x,12,out=y)

array([ 0., 12., 24., 36., 48.])

In [56]:
a = np.arange(5)
b = np.zeros(10)
np.power(2,x,out=b[::2])
b

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [57]:
x = np.arange(1,6)
np.add.reduce(x), np.multiply.reduce(x), np.add.accumulate(x), np.multiply.accumulate(x)

(15,
 120,
 array([ 1,  3,  6, 10, 15], dtype=int32),
 array([  1,   2,   6,  24, 120], dtype=int32))

In [58]:
#外積
x = np.arange(1,5)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [59]:
#summerise
x = np.random.random(1000000)
%timeit np.sum(x) #快多了
%timeit sum(x)

2.18 ms ± 348 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
118 ms ± 28.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [60]:
np.sum(x), sum(x)

(499998.3669244014, 499998.36692440376)

In [61]:
#as same as
np.max(x), np.min(x), x.max(), x.min()

(0.9999992267897795,
 9.828372018461096e-07,
 0.9999992267897795,
 9.828372018461096e-07)

In [62]:
x.mean(), x.std()

(0.49999836692440136, 0.2884486245987413)

In [63]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
y.sum(axis=0), y.sum(axis=1)

(array([ 5,  7,  9, 11, 13]), array([10, 35]))

In [65]:
a = np.random.random((10,3))
a

array([[0.46029988, 0.72760286, 0.54824655],
       [0.94155734, 0.34589603, 0.47300195],
       [0.24607925, 0.10717144, 0.16069862],
       [0.03748846, 0.70121681, 0.3885371 ],
       [0.53926615, 0.30701899, 0.58860685],
       [0.43041648, 0.89626776, 0.17788204],
       [0.30040217, 0.87488261, 0.10943062],
       [0.12300136, 0.99217182, 0.91724458],
       [0.40890527, 0.6010687 , 0.18606227],
       [0.50263745, 0.50685954, 0.71665002]])

In [66]:
a.mean(axis=0)

array([0.39900538, 0.60601566, 0.42663606])

In [67]:
#broadcasting，可去查詢broadcasting詳細規則
#全部的數減去平均值
b = a - a.mean(axis=0)
b

array([[ 0.0612945 ,  0.1215872 ,  0.12161049],
       [ 0.54255195, -0.26011962,  0.04636589],
       [-0.15292613, -0.49884421, -0.26593744],
       [-0.36151692,  0.09520116, -0.03809896],
       [ 0.14026077, -0.29899667,  0.16197079],
       [ 0.0314111 ,  0.2902521 , -0.24875403],
       [-0.09860321,  0.26886695, -0.31720544],
       [-0.27600402,  0.38615616,  0.49060852],
       [ 0.00989989, -0.00494696, -0.24057379],
       [ 0.10363207, -0.09915612,  0.29001396]])

In [68]:
#驗算，都接近0
b.mean(axis=0)

array([1.11022302e-17, 4.44089210e-17, 5.55111512e-18])

In [80]:
#sort
x = np.random.randint(1,100,size=10)
np.sort(x)

array([26, 31, 40, 52, 55, 63, 67, 70, 77, 90])

In [84]:
x = np.random.randint(1,100,[4,4])
np.sort(x, axis =0)

array([[12,  8, 11, 48],
       [59, 79, 46, 64],
       [61, 81, 54, 74],
       [96, 87, 82, 86]])

In [87]:
np.sort(x, axis=1)

array([[11, 12, 79, 86],
       [ 8, 46, 48, 96],
       [54, 59, 64, 81],
       [61, 74, 82, 87]])

In [8]:
#partition
x = np.random.randint(1,100,size=10)
#最小個值放左側，順序隨意
np.partition(x,3)

array([56, 39, 20, 67, 79, 86, 72, 80, 84, 90])

In [16]:
x = np.random.randint(1,100,size=20)
x = x.reshape(4,5)
np.partition(x,2,axis=1)

array([[12, 27, 29, 89, 96],
       [ 6, 11, 66, 70, 70],
       [31, 38, 83, 92, 83],
       [15, 57, 58, 90, 84]])