In [4]:
import numpy
numpy.__version__

'1.16.5'

In [2]:
import numpy as np

In [9]:
np.array([1, 5, 3])

array([1, 5, 3])

In [11]:
np.array([3.24, 3, 5])#自動轉成同型態

array([3.24, 3.  , 5.  ])

In [13]:
np.array(['cat',3])

array(['cat', '3'], dtype='<U3')

In [19]:
np.array([3, 5],dtype=str)

array(['3', '5'], dtype='<U1')

In [43]:
np.array([(3, 2),(3, 5),(7, 6)])#多維

array([[3, 2],
       [3, 5],
       [7, 6]])

In [22]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [28]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((2, 5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [46]:
np.full((2,5,3),3.2)

array([[[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]],

       [[3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2],
        [3.2, 3.2, 3.2]]])

In [2]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [4]:
np.random.random((2, 5)) #uniform

array([[0.44378915, 0.14472199, 0.31672113, 0.27456506, 0.55364216],
       [0.40877563, 0.34134866, 0.30603692, 0.07280939, 0.84478437]])

In [5]:
np.random.normal(0,1,(2,5)) #normal distribution mean 0 std 1  

array([[ 1.80248422, -1.24115579, -0.65776034,  0.72301025,  1.09410326],
       [-1.6150139 ,  1.11626806, -1.37602427, -1.2575822 ,  0.32588485]])

In [10]:
np.random.randint(0,100,(2,5))

array([[59, 90, 96, 26,  7],
       [40, 51, 18, 82, 58]])

In [12]:
np.eye(3)*4 #單位矩陣

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [8]:
a = np.random.randint(10,size=(2,5,3))
a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes
#itemsize(byte), nbytes(byte)
# in general, itemsize * size = nbytes

(3, (2, 5, 3), 30, dtype('int32'), 4, 120)

In [13]:
#slice
x = np.array([(12, 5, 2, 4), (7, 6, 8, 8), (1, 6, 7, 7)])
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
x[1:,1:] #row col

array([[6, 8, 8],
       [6, 7, 7]])

In [18]:
x[1:,2]

array([8, 7])

In [20]:
x[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [22]:
x[:,1] #單取col成array

array([5, 6, 6])

In [24]:
x[2,:] #單取row成array

array([1, 6, 7, 7])

In [25]:
#np的slice是參考，跟python原本list的slice是複製不一樣
#np slice出來得參考會影響到原本的np array
#要建立np array的複本要用 .copy()

In [7]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
#相同維度的串接
x1 = np.array([1, 2, 3])
y1 = np.array([4, 5, 6])

In [29]:
np.concatenate([x1,y1])

array([1, 2, 3, 4, 5, 6])

In [48]:
#不同維度的串接
x2 = np.array([(3, 2),(3, 5),(7, 6)])
y2 = np.array([(5, 0)])
z2 = np.array([[1], [3], [6]])

In [53]:
x2

array([[3, 2],
       [3, 5],
       [7, 6]])

In [55]:
y2

array([[5, 0]])

In [56]:
z2

array([[1],
       [3],
       [6]])

In [40]:
np.vstack( [x2, y2] )

array([[3, 2],
       [3, 5],
       [7, 6],
       [5, 0]])

In [57]:
np.hstack( [x2, z2] )

array([[3, 2, 1],
       [3, 5, 3],
       [7, 6, 6]])

In [63]:
a, b, c = np.split(np.array((2,5,6,7,3,6,3,6)), [2,5]  )
a, b, c

(array([2, 5]), array([6, 7, 3]), array([6, 3, 6]))

In [68]:
a, b = np.vsplit( np.arange(16).reshape([4,4]), [2] )
a, b

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [72]:
c, d = np.hsplit( np.arange(16).reshape([4,4]), [2] )
c, d

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [3]:
#np的向量化計算 比python自己的迭代快很多
np.random.seed(0)

def reciprocals( vals ):
    result = np.empty(len(vals))
    for i in range(len(vals)):
        result[i] = 1/vals[i]
    return result

In [4]:
%timeit reciprocals(np.random.randint(1,100,size=1000000)) #slow

208 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit (1/np.random.randint(1,10,size=1000000)) #fast

13.7 ms ± 60.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
