In [1]:
import numpy
import numpy as np
numpy.__version__

'1.19.2'

In [2]:
#相同維度的串接
x1 = np.array([1, 2, 3])
y1 = np.array([4, 5, 6])

In [3]:
np.concatenate([x1,y1])

array([1, 2, 3, 4, 5, 6])

In [4]:
#不同維度的串接
x2 = np.array([(3, 2),(3, 5),(7, 6)])
y2 = np.array([(5, 0)])
z2 = np.array([[1], [3], [6]])

In [5]:
x2

array([[3, 2],
       [3, 5],
       [7, 6]])

In [6]:
y2

array([[5, 0]])

In [7]:
z2

array([[1],
       [3],
       [6]])

In [8]:
np.vstack( [x2, y2] )

array([[3, 2],
       [3, 5],
       [7, 6],
       [5, 0]])

In [9]:
np.hstack( [x2, z2] )

array([[3, 2, 1],
       [3, 5, 3],
       [7, 6, 6]])

In [10]:
a, b, c = np.split(np.array((2,5,6,7,3,6,3,6)), [2,5]  )
a, b, c

(array([2, 5]), array([6, 7, 3]), array([6, 3, 6]))

In [12]:
a, b = np.vsplit( np.arange(16).reshape([4,4]), [2] )
a, b

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [15]:
c, d = np.hsplit( np.arange(16).reshape([4,4]), [2] )
c, d

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [16]:
#預先決定輸出的記憶體
x = np.arange(5)
y = np.empty(5)
np.multiply(x,12,out=y)

array([ 0., 12., 24., 36., 48.])

In [18]:
a = np.arange(5)
b = np.zeros(10)
np.power(2, a, out=b[::2])
b

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [20]:
x = np.arange(1,6)
np.add.reduce(x), np.multiply.reduce(x), np.add.accumulate(x), np.multiply.accumulate(x)

(15, 120, array([ 1,  3,  6, 10, 15]), array([  1,   2,   6,  24, 120]))

In [21]:
x = np.arange(1,5)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [22]:
#summerise
x = np.random.random(1000000)
%timeit np.sum(x) #快多了
%timeit sum(x)

582 µs ± 7.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
143 ms ± 3.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
np.sum(x), sum(x)

(499938.68327102746, 499938.68327102874)

In [24]:
#as same as
np.max(x), np.min(x), x.max(), x.min()

(0.9999999121345138,
 3.377604154142233e-07,
 0.9999999121345138,
 3.377604154142233e-07)

In [26]:
x.mean(), x.std()

(0.4999386832710275, 0.2885237732357071)

In [28]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
y.sum(axis=0), y.sum(axis=1)

(array([ 5,  7,  9, 11, 13]), array([10, 35]))

In [40]:
a = np.random.random((10,3))
a

array([[0.38579035, 0.52163565, 0.08925813],
       [0.00247175, 0.75023199, 0.85691979],
       [0.57988934, 0.16124259, 0.2173687 ],
       [0.73712834, 0.11221774, 0.01010835],
       [0.93099786, 0.98301607, 0.21323322],
       [0.68907092, 0.36655736, 0.63642231],
       [0.50013187, 0.21484991, 0.44700876],
       [0.6769077 , 0.62409857, 0.4985715 ],
       [0.91435325, 0.11398199, 0.09217122],
       [0.72722479, 0.36305654, 0.97232834]])

In [41]:
a.mean(axis=0)

array([0.61439662, 0.42108884, 0.40333903])

In [42]:
#broadcasting，向量化的概念
#全部的數減去平均值
b = a - a.mean(axis=0)
b

array([[-0.22860627,  0.10054681, -0.3140809 ],
       [-0.61192486,  0.32914315,  0.45358076],
       [-0.03450728, -0.25984625, -0.18597033],
       [ 0.12273172, -0.3088711 , -0.39323068],
       [ 0.31660124,  0.56192723, -0.19010581],
       [ 0.0746743 , -0.05453148,  0.23308327],
       [-0.11426475, -0.20623893,  0.04366973],
       [ 0.06251109,  0.20300973,  0.09523247],
       [ 0.29995664, -0.30710685, -0.31116782],
       [ 0.11282817, -0.0580323 ,  0.56898931]])

In [43]:
#驗算，都接近0
b.mean(axis=0)

array([4.44089210e-17, 1.11022302e-17, 3.33066907e-17])

In [44]:
#sort
x = np.random.randint(1,100,size=10)
np.sort(x)

array([ 8, 20, 20, 27, 42, 59, 71, 74, 76, 85])

In [45]:
x = np.random.randint(1,100,[4,4])
np.sort(x, axis =0)

array([[34,  1,  3, 43],
       [46,  8, 16, 47],
       [79, 75, 65, 69],
       [87, 84, 72, 71]])

In [46]:
np.sort(x, axis=1)

array([[47, 65, 75, 87],
       [ 1, 69, 72, 79],
       [ 8, 16, 43, 46],
       [ 3, 34, 71, 84]])

In [47]:
#partition
x = np.random.randint(1,100,size=10)
#最小個值放左側，順序隨意
np.partition(x,3)

array([ 1,  3, 29, 29, 40, 49, 81, 70, 59, 65])

In [48]:
x = np.random.randint(1,100,size=20)
x = x.reshape(4,5)

x, np.partition(x,2,axis=1)

(array([[94, 69, 70, 63, 16],
        [92, 81, 57, 30, 99],
        [11, 81, 32, 47, 38],
        [33, 84, 72, 88, 11]]),
 array([[16, 63, 69, 70, 94],
        [30, 57, 81, 92, 99],
        [11, 32, 38, 47, 81],
        [11, 33, 72, 88, 84]]))